config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  get 'settings', to: 'pages#settings', as: 'settings'
  post 'change_preference', to: 'users#change_preference', as: 'change_preference'
  post 'create_meetup', to: 'meet_up_times#create', as: 'create_meetup'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'check_match', to: 'users#check_match', as: 'check_match'
    resources :swipes, only: [:create]
    resources :matches, only: [:index, :show] do
      post 'accept', to: 'meet_up_times#accept', as: 'accept'
      post 'decline', to: 'meet_up_times#decline', as: 'decline'
      post 'confirmed', to: 'meet_up_times#confirmed?', as: 'confirmed'
      resources :bars, only: [:show]
    end
    post 'swiped_right', to: 'swipes#swiped_right', as: 'swiped_right'
    post 'swiped_left', to: 'swipes#swiped_left', as: 'swiped_left'
  end
  # resources :coupons, only [:show, :edit, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :swipes, foreign_key: "swiper_id", class_name: "Swipe"
  has_many :first_matches, foreign_key: "first_user_id", class_name: "Match"
  has_many :last_matches, foreign_key: "last_user_id", class_name: "Match"

  has_many :photos

  def matches
    first_matches + last_matches
  end

  def self.age_calculate(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.first_name
      user.gender = auth.extra.raw_info.gender
      user.image = auth.info.image
      user.age = age_calculate(Date.strptime(auth.extra.raw_info.birthday, '%m/%d/%Y')) # assuming the user model has an image
      user.preference = user.gender == 'male' ? 'female' : 'male'
      user.photos = [auth.info.image]
      user.save
      propic_id = auth.extra.raw_info.albums['data'].find { |album| album['name'] == "Profile Pictures" }['id']
      album_url = "https://graph.facebook.com/v4.0/#{propic_id}/photos?access_token=#{auth.credentials.token}"
      user_serialized = open(album_url).read
      profile_data = JSON.parse(user_serialized)
      profile_data['data'].first(5).each do |image|
        url = "https://graph.facebook.com/v4.0/#{image['id']}/picture?access_token=#{auth.credentials.token}&width=600"
        photo = Photo.new(user: user)
        photo.remote_photo_url = url
        photo.save!
      end
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:change_preference, :check_match]
  def index
    @swiped_id = []
    if current_user.swipes == []
      @users = User.where.not('id = ?', current_user.id).where('gender = ?', current_user.preference).shuffle
    else
      current_user.swipes.each { |swipe| @swiped_id << swipe.swipee.id }
      @users = User.where.not('id = ?', current_user.id).where("id NOT IN (?)", @swiped_id).where('gender = ?', current_user.preference).shuffle
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to settings_path
  end

  def change_preference
    user = current_user
    user.preference = params[:preference]
    user.save
  end

  def check_match
    @swiped_user = User.find(params[:user_id])
    @swiped = @swiped_user.swipes.map(&:swipee)
    if @swiped.include?(current_user)
      create_match
      render_page(@swiped_user)
    else
      render json: { match: false }
    end
  end

  def render_page(swiped_user)
    render json: { match: true, name: swiped_user.name, photo: swiped_user.photos[0].photo.url, match: @match.id, user: current_user.id }
  end

  def create_match
    bar = Bar.all.sample
    initial_date = generate_meet_up_time
    meet_up_time = MeetUpTime.create(meet_up_time: initial_date, first_user_accepted: false, last_user_accepted: false)
    used = false
    expiry_date = Time.now + (2 * 7 * 24 * 60 * 60)
    location_validated = false
    content = "1 free drink"
    coupon = Coupon.create(used: used, expiry_date: expiry_date, location_validated: location_validated, content: content)
    @match = Match.create(first_user: current_user, last_user: @swiped_user, bar: bar, meet_up_time: meet_up_time, coupon: coupon)
  end

  def generate_meet_up_time
    @date = rand(Date.today..Date.today + 14).to_datetime
    return @date.change(hour: rand(17..22))
  end

  private

  def user_params
    params.require(:user).permit(:bio)
  end
end

app/views/users/_match_alert.html.erb
<div id="matchModal" class="modal fade match-modal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div id="match-modal-insert" class="modal-body">
        <h2 class="modal-title"></h2>
        <img class='match-modal-image' src=''>
        <a href='#' class='checkout btn-alert blue'>Check out the bar</a>
        <a type="button" href="#" class="btn-alert red" data-dismiss="modal">Keep swiping</a>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="bio-edit-container">
  <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_field :bio, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'shared/navbar' %>
<div class="tinder">
  <div class="tinder--status">
    <i class="fas fa-times"></i>
    <i class="fa fa-heart"></i>
  </div>
  <div class="tinder--cards">
    <% @users.each do |user| %>
      <% photo_urls = user.photos.map { |image| image.photo.url } %>
      <div class="tinder--card" data-photos="<%= JSON.generate(photo_urls) %>" data-photo-idx="0" id=<%= "card#{user.id}" %> style="background-image: linear-gradient(180deg, rgba(0,0,0,0) 80%, rgba(0,0,0,0.8) 100%), url('<%= photo_urls[0] %>'); background-size: auto 100%; background-position: center;" >
        <h3><%= "#{user.name}, #{user.age}" %></h3>
        <%#= link_to 'checkmatch', user_check_match_path(user), remote: true %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'match_alert' %>

app/views/users/show.html.erb
<h1>THis is the show page</h1>