config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  get 'settings', to: 'pages#settings', as: 'settings'
  post 'change_preference', to: 'users#change_preference', as: 'change_preference'
  post 'create_meetup', to: 'meet_up_times#create', as: 'create_meetup'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'check_match', to: 'users#check_match', as: 'check_match'
    resources :swipes, only: [:create]
    resources :matches, only: [:index, :show] do
      post 'accept', to: 'meet_up_times#accept', as: 'accept'
      post 'decline', to: 'meet_up_times#decline', as: 'decline'
      post 'confirmed', to: 'meet_up_times#confirmed?', as: 'confirmed'
      resources :bars, only: [:show]
    end
    post 'swiped_right', to: 'swipes#swiped_right', as: 'swiped_right'
    post 'swiped_left', to: 'swipes#swiped_left', as: 'swiped_left'
  end
  # resources :coupons, only [:show, :edit, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<!-- Logo -->
<% if user_signed_in? %>
  <%= link_to users_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "skal_logo.png", height: 50 %>
  <% end %>
<% else %>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "skal_logo.png", height: 50 %>
  <% end %>
<% end %>

app/views/shared/_matches_button.html.erb
<%= link_to user_matches_path(current_user) do %>
  <%= image_tag 'beer.png', class: "avatar"%>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <%= render 'shared/settings_button' %>
  <%= render 'shared/logo'%>
  <%= render 'shared/matches_button'%>
</div>

app/views/shared/_settings_button.html.erb
<%= link_to settings_path do %>
  <%= image_tag 'profile.png', class: "avatar"%>
<% end %>

app/views/shared/_settings_navbar.html.erb
<div class="navbar-wagon">
  <div class='placeholder'></div>
  <%= render 'shared/settings_button' %>
  <%= render 'shared/logo'%>
</div>