config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  get 'settings', to: 'pages#settings', as: 'settings'
  post 'change_preference', to: 'users#change_preference', as: 'change_preference'
  post 'create_meetup', to: 'meet_up_times#create', as: 'create_meetup'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'check_match', to: 'users#check_match', as: 'check_match'
    resources :swipes, only: [:create]
    resources :matches, only: [:index, :show] do
      post 'accept', to: 'meet_up_times#accept', as: 'accept'
      post 'decline', to: 'meet_up_times#decline', as: 'decline'
      post 'confirmed', to: 'meet_up_times#confirmed?', as: 'confirmed'
      resources :bars, only: [:show]
    end
    post 'swiped_right', to: 'swipes#swiped_right', as: 'swiped_right'
    post 'swiped_left', to: 'swipes#swiped_left', as: 'swiped_left'
  end
  # resources :coupons, only [:show, :edit, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="signin-container hidden-sm hidden-md hidden-lg">
  <div class="home-container">
    <h1>SKÅL</h1>
    <%= image_tag "skal_logo_white.png", class:'skal_logo', alt: "alttext" %>
    <div id="beer-container">
      <!-- <div class="pour"></div> -->
      <div id="beaker">
        <div class="beer-foam">
          <div class="foam-1"></div>
          <div class="foam-2"></div>
          <div class="foam-3"></div>
          <div class="foam-4"></div>
          <div class="foam-5"></div>
          <div class="foam-6"></div>
          <div class="foam-7"></div>
        </div>

        <div id="liquid">

          <div class="bubble bubble1"></div>
          <div class="bubble bubble2"></div>
          <div class="bubble bubble3"></div>
          <div class="bubble bubble4"></div>
          <div class="bubble bubble5"></div>
        </div>
      </div>
    </div>
    <p class='tagline'>First round's on us!</p>
    <%= link_to user_facebook_omniauth_authorize_path, class:'fb-signup' do %>
      Sign in with Facebook <i class="fab fa-facebook-square"></i>
    <% end %>
  </div>
</div>

<div class="hidden-xs text-top-center">
  <div class="banner">
    <div class="background"></div>
  </div>
  <div class="banner-content">
    <h1 id="text-header">SKÅL</h1>
    <h2 id="text-sub-header">First round's on us.</h2>
    <p>Explore SKÅL on a mobile device now.</p>
  </div>
</div>



<%= content_for(:after_js) do %>
  <%= javascript_pack_tag "homepage" %>
<% end %>

app/views/pages/settings.html.erb
<%= render 'shared/settings_navbar' %>
<div class="settings-container">
  <div class="profile-pic-container clickable" data-toggle="modal" data-target=".user-modal">
    <%= image_tag current_user.photos.first.photo.url, class:'profile-pic', alt: "profile-pic" %>
  </div>

  <h2><%= "#{current_user.name}, #{current_user.age}" %></h2>
  <%= link_to "Edit profile", edit_user_path(current_user)  %>
  <div class="preference">
    <p>Preference</p>
    <div class="checked-state contact-type">
      <%= link_to change_preference_path(preference: 'male'), remote: true, method: :post do %>
        <span class='<%= "option-circle male #{@male_on}" %>'><i class="fas fa-mars"></i></span>
      <% end %>

      <%= link_to change_preference_path(preference: 'female'), remote: true, method: :post do %>
        <span class='<%= "option-circle female #{@female_on}" %>'><i class="fas fa-venus"></i></span>
      <% end %>
    </div>
  </div>

  <%= link_to destroy_user_session_path, method: :delete, class:'btn-logout' do %>
    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
  <% end %>
</div>

<%= render 'matches/user_modal', user: current_user %>


<%= content_for(:after_js) do %>
  <%= javascript_pack_tag "preference" %>
<% end %>