config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  get 'settings', to: 'pages#settings', as: 'settings'
  post 'change_preference', to: 'users#change_preference', as: 'change_preference'
  post 'create_meetup', to: 'meet_up_times#create', as: 'create_meetup'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'check_match', to: 'users#check_match', as: 'check_match'
    resources :swipes, only: [:create]
    resources :matches, only: [:index, :show] do
      post 'accept', to: 'meet_up_times#accept', as: 'accept'
      post 'decline', to: 'meet_up_times#decline', as: 'decline'
      post 'confirmed', to: 'meet_up_times#confirmed?', as: 'confirmed'
      resources :bars, only: [:show]
    end
    post 'swiped_right', to: 'swipes#swiped_right', as: 'swiped_right'
    post 'swiped_left', to: 'swipes#swiped_left', as: 'swiped_left'
  end
  # resources :coupons, only [:show, :edit, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :bar
  belongs_to :meet_up_time
  belongs_to :coupon
  belongs_to :first_user, class_name: "User"
  belongs_to :last_user, class_name: "User"

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.where(first_user: current_user).or(Match.where(last_user: current_user))
  end

  def show
    @match = Match.find(params[:id])
    @your_date = @match.first_user == current_user ? @match.last_user : @match.first_user
    @bar = @match.bar
    # @markers =
    #   [{
    #     lng: @bar.longitude,
    #     lat: @bar.latitude
    #   }]
  end
end

app/views/matches/_bar_modal.html.erb
<div id="barModal" class="modal fade bar-modal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div id="bar-modal-insert" class="bar-modal-body">
        <h2 class="modal-title"></h2>
        <% bar.photos.each_with_index do |image, idx| %>
          <% if idx == 1  %>
            <div class="bar-description"><%= bar.description %></div>
          <% end %>
          <%= image_tag image.photo.url, class:'bar-modal-image', alt: "alttext" %>
        <% end %>
        <a type="button" href="#" class="btn-close stick" data-dismiss="modal"><i class="fas fa-times"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/matches/_coupon_modal.html.erb
<div id="couponModal" class="modal fade coupon-modal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div id="coupon-modal-insert" class="modal-body">
        <h3 class="modal-title">1 free drink at <br><%= bar.name %> </h3>
        <%= image_tag "qrcode.png", class:'qrcode', alt: "alttext" %>
        <a type="button" href="#" class="btn-close stick" data-dismiss="modal"><i class="fas fa-times"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/matches/_match_accept_waiting.html.erb
<div class="match-accept-waiting">
  <p>Waiting for <%= image_tag user.photos[0].photo.url, class:'avatar', alt: "alttext" %> <strong><%= user.name %></strong> to respond...</p>
</div>

app/views/matches/_match_ask_time.html.erb
<div class="match-ask-time">
  <div class="calender-header">
    <p>Free drink with <strong><%= user.name %></strong></p>
  </div>
  <div class="calender-date">
   <h3><%= @match.meet_up_time.meet_up_time.strftime("%e %B at %l:%M%p")%></h3>
  </div>
</div>

<div class="match-response">
  <div class="match-accept btn-respond accept" data-user="<%= current_user.id %>" data-match="<%= @match.id %>"><i class="fas fa-check"></i></div>

  <div class="match-decline btn-respond decline" data-user="<%= current_user.id %>" data-match="<%= @match.id %>">
    <i class="fas fa-sync-alt"></i></div>
</div>

app/views/matches/_match_bar.html.erb
<div class="match-bar" style="background-image: linear-gradient(180deg, rgba(0,0,0,0) 70%, rgba(0,0,0,0.9) 100%), url(<%= image_path the_match.bar.photos[0].photo.url %>); background-position: center; background-size: cover;">
  <div class="bar-content">
    <p ><i class="fas fa-map-marker-alt"></i> <%= the_match.bar.name %></p>

    <div class="bar-icons">
      <a href="#" class="clickable" data-toggle="modal" data-target=".bar-modal"><i class="fas fa-info-circle"></i></a>
      <%= link_to "https://www.google.com/maps?saddr=My+Location&daddr=#{bar.location}", id: "google-directions" do %>
        <i class="fas fa-directions"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/matches/_match_both_accept.html.erb
<div class="match-both-accept">
  <p><i class="fas fa-check-circle"></i> Both have accepted! 😱 <strong>SKÅL</strong>! 🍻</p>
  <a href="#" class="clickable coupon" data-toggle="modal" data-target=".coupon-modal">
    COUPON
  </a>
</div>

app/views/matches/_match_navbar.html.erb
<div class="navbar-wagon">
  <div class="go-back">
    <%= link_to user_matches_path(current_user) do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class="avatar-with-name" data-toggle="modal" data-target=".user-modal">
    <%= image_tag user.photos.first.photo.url, class:'avatar', alt: "alttext" %>
    <p><%= user.name %></p>
  </div>
  <div class='placeholder'></div>
</div>

app/views/matches/_match_opposite_responded.html.erb
<div class="match-opposite-responded">
  <p><%= image_tag user.photos[0].photo.url, class:'avatar', alt: "alttext" %> <strong><%= user.name %></strong> has accepted!</p>
</div>

app/views/matches/_user_modal.html.erb
<div id="userModal" class="modal fade user-modal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div id="match-modal-insert" class="modal-body">
        <h2 class="modal-title"></h2>
        <% user.photos.reverse.each_with_index do |image, idx| %>
          <% if idx == 1 && user.bio != ""  %>
            <div class="user-description"><%= user.bio %></div>
          <% end %>
          <%= image_tag image.photo.url, class:'user-modal-image', alt: "alttext" %>
        <% end %>
        <a type="button" href="#" class="btn-close stick" data-dismiss="modal"><i class="fas fa-times"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/matches/index.html.erb
<div class="navbar-wagon">
  <%= render 'shared/logo'%>
  <%= render 'shared/matches_button'%>
  <div class="placeholder"></div>
</div>
<div class="new-matches-container">
  <div class="site-wrap">
    <div class="messages">
      <div class="header">MATCHES</div>
    </div>
  </div>
</div>
  <% @matches.each do |match| %>
    <%= link_to user_match_path(current_user, match), class: 'link-decoration' do %>
      <div class="message">
        <img class="avatar-large" src="<%= match.first_user == current_user ? match.last_user.photos.first.photo : match.first_user.photos.first.photo %>">
        <div class="message-body">
          <h6><%= match.first_user == current_user ? match.last_user.name : match.first_user.name %></h6>
          <p>
            <%= match.coupon.content %>
          </p>
        </div>
        <div class="message-status">
          <% if match.coupon.used %>
            <i class="used fas fa-circle"></i>
          <% elsif match.coupon.in_past? && match.meet_up_time.one_pending? %>
            <i class="expired fas fa-circle"></i>
          <% elsif match.coupon.in_future? && match.meet_up_time.one_pending? %>
            <i class="yet-agreed fas fa-circle"></i>
          <% elsif match.coupon.in_future? && match.meet_up_time.both_accepted?  %>
            <i class="pending fas fa-circle"></i>
          <% end %>
        </div>
      </div>
    <% end %>
<% end %>

app/views/matches/show.html.erb
<%= render 'match_navbar', user: @your_date %>

<div class="match-show-container">
  <%= render 'match_bar', the_match: @match, bar: @bar %>
  <%= render 'match_ask_time', user: @your_date %>
  <%= render 'match_accept_waiting', user: @your_date %>
  <%= render 'match_opposite_responded', user: @your_date %>
  <%= render 'match_both_accept', user: @your_date %>
</div>

<%= render 'user_modal', user: @your_date %>
<%= render 'bar_modal', bar: @bar %>
<%= render 'coupon_modal', bar: @bar %>



<%= content_for(:after_js) do %>
  <%= javascript_pack_tag "matchShow" %>
<% end %>

  <!-- <div class="match-user" style="background-image: linear-gradient(180deg, rgba(0,0,0,0) 70%, rgba(0,0,0,0.8) 100%), url(<%= image_path @your_date.photos[0].photo.url %>); background-position: center; background-size: cover;"></div> -->